//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.586
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbifluxWcfService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/AmbifluxWcfService")]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname
        {
            get
            {
                return this.firstnameField;
            }
            set
            {
                this.firstnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname
        {
            get
            {
                return this.lastnameField;
            }
            set
            {
                this.lastnameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceRecord", Namespace="http://schemas.datacontract.org/2004/07/AmbifluxWcfService")]
    public partial class ResourceRecord : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int LocationIdField;
        
        private string NameField;
        
        private int ResourceIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationId
        {
            get
            {
                return this.LocationIdField;
            }
            set
            {
                this.LocationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResourceId
        {
            get
            {
                return this.ResourceIdField;
            }
            set
            {
                this.ResourceIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderHeaderRecord", Namespace="http://schemas.datacontract.org/2004/07/AmbifluxWcfService")]
    public partial class OrderHeaderRecord : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CustomerFirstNameField;
        
        private string CustomerLastNameField;
        
        private string ObjetDemandeExpressField;
        
        private string OrderDateField;
        
        private int OrderIdField;
        
        private string OrderNoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerFirstName
        {
            get
            {
                return this.CustomerFirstNameField;
            }
            set
            {
                this.CustomerFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerLastName
        {
            get
            {
                return this.CustomerLastNameField;
            }
            set
            {
                this.CustomerLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjetDemandeExpress
        {
            get
            {
                return this.ObjetDemandeExpressField;
            }
            set
            {
                this.ObjetDemandeExpressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderDate
        {
            get
            {
                return this.OrderDateField;
            }
            set
            {
                this.OrderDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNo
        {
            get
            {
                return this.OrderNoField;
            }
            set
            {
                this.OrderNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SRMARecord", Namespace="http://schemas.datacontract.org/2004/07/AmbifluxWcfService")]
    public partial class SRMARecord : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ModeField;
        
        private string NameField;
        
        private int ResourceIdField;
        
        private int StateField;
        
        private int TaskField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mode
        {
            get
            {
                return this.ModeField;
            }
            set
            {
                this.ModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResourceId
        {
            get
            {
                return this.ResourceIdField;
            }
            set
            {
                this.ResourceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Task
        {
            get
            {
                return this.TaskField;
            }
            set
            {
                this.TaskField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IAmbiflux")]
public interface IAmbiflux
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmbiflux/GetAllEmployeesMethod", ReplyAction="http://tempuri.org/IAmbiflux/GetAllEmployeesMethodResponse")]
    AmbifluxWcfService.Employee[] GetAllEmployeesMethod();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmbiflux/GetEmployeeById", ReplyAction="http://tempuri.org/IAmbiflux/GetEmployeeByIdResponse")]
    AmbifluxWcfService.Employee GetEmployeeById(string resourceId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmbiflux/GetResourceById", ReplyAction="http://tempuri.org/IAmbiflux/GetResourceByIdResponse")]
    AmbifluxWcfService.ResourceRecord GetResourceById(string resourceId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmbiflux/GetOrderHeaderById", ReplyAction="http://tempuri.org/IAmbiflux/GetOrderHeaderByIdResponse")]
    AmbifluxWcfService.OrderHeaderRecord GetOrderHeaderById(string orderHeaderId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmbiflux/GetSRMA", ReplyAction="http://tempuri.org/IAmbiflux/GetSRMAResponse")]
    AmbifluxWcfService.SRMARecord GetSRMA();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmbiflux/NewSRMARequest", ReplyAction="http://tempuri.org/IAmbiflux/NewSRMARequestResponse")]
    string NewSRMARequest(string phoneNumber, string locationId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IAmbifluxChannel : IAmbiflux, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AmbifluxClient : System.ServiceModel.ClientBase<IAmbiflux>, IAmbiflux
{
    
    public AmbifluxClient()
    {
    }
    
    public AmbifluxClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AmbifluxClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AmbifluxClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AmbifluxClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public AmbifluxWcfService.Employee[] GetAllEmployeesMethod()
    {
        return base.Channel.GetAllEmployeesMethod();
    }
    
    public AmbifluxWcfService.Employee GetEmployeeById(string resourceId)
    {
        return base.Channel.GetEmployeeById(resourceId);
    }
    
    public AmbifluxWcfService.ResourceRecord GetResourceById(string resourceId)
    {
        return base.Channel.GetResourceById(resourceId);
    }
    
    public AmbifluxWcfService.OrderHeaderRecord GetOrderHeaderById(string orderHeaderId)
    {
        return base.Channel.GetOrderHeaderById(orderHeaderId);
    }
    
    public AmbifluxWcfService.SRMARecord GetSRMA()
    {
        return base.Channel.GetSRMA();
    }
    
    public string NewSRMARequest(string phoneNumber, string locationId)
    {
        return base.Channel.NewSRMARequest(phoneNumber, locationId);
    }
}
